export const AMBASSADOR_DESCRIPTION = {
    ru: `
  Шавкат Миромонович Мирзиёев родился 24 июля 1957 года в Зааминском районе Джизакской области в семье врача. По национальности – узбек. Образование – высшее, в 1981 году окончил Ташкентский институт инженеров ирригации и механизации сельского хозяйства, получив специальность инженера-механика. Кандидат технических наук, доцент.
  Начал трудовую деятельность в 1981 году в Ташкентском институте инженеров ирригации и механизации сельского хозяйства, работал младшим научным сотрудником, старшим преподавателем, доцентом, проректором по учебной работе.
  В 1990 году избран депутатом Верховного Совета республики, был председателем Мандатной комиссии.
  В 1992 году был назначен хокимом Мирзо-Улугбекского района города Ташкента. В 1996–2001 годах работал в должности хокима Джизакской области, в 2001–2003 годах – хокимом Самаркандской области, внес большой вклад в социально-экономическое развитие вышеназванных района и областей.
  Работая в органах исполнительной власти, одновременно в 1995–2003 годах в качестве депутата Олий Мажлиса Республики Узбекистан активно и плодотворно участвовал в разработке и принятии важных законодательных документов, направленных на политическое и социально-экономическое развитие страны и реализацию демократических реформ.
  Ш.М. Мирзиёев в 2003 году был утвержден Премьер-министром Республики Узбекистан и еще три раза – в 2005, 2010, 2015 годах – утверждался на этот пост палатами Олий Мажлиса.
  С первых лет независимости нашей Родины Ш.М. Мирзиёев, заслужив высокое доверие Первого Президента Республики Узбекистан Ислама Каримова, самоотверженно работает как его соратник и единомышленник.
  Ш.М. Мирзиёев на посту главы правительства проявил свой высокий потенциал и выдающиеся организаторские способности в реализации широкомасштабных социально-экономических реформ, модернизации и обновлении страны, осуществлении крупных и уникальных проектов, развитии и обеспечении приоритета частной собственности, кардинальном повышении доли малого бизнеса и частного предпринимательства в экономике и дальнейшем укреплении их правовой защиты.
    `,
    uz: `
  Shavkat Miromonovich Mirziyoyev 1957-yil 24-iyulda Jizzax viloyatining Zomin tumanida shifokor oilasida tug‘ilgan. Millati — o‘zbek. Ma’lumoti — oliy, 1981-yilda Toshkent irrigatsiya va qishloq xo‘jaligini mexanizatsiyalash muhandislari institutini muhandis-mexanik mutaxassisligi bo‘yicha tamomlagan. Texnika fanlari nomzodi, dotsent.
  Mehnat faoliyatini 1981-yilda Toshkent irrigatsiya va qishloq xo‘jaligini mexanizatsiyalash muhandislari institutida boshlagan, kichik ilmiy xodim, katta o‘qituvchi, dotsent, o‘quv ishlari bo‘yicha prorektor lavozimlarida ishlagan.
  1990-yilda O‘zbekiston Respublikasi Oliy Kengashining deputati etib saylangan, Mandat komissiyasi raisi bo‘lgan.
  1992-yilda Toshkent shahri Mirzo Ulug‘bek tumani hokimi lavozimiga tayinlangan. 1996–2001-yillarda Jizzax viloyati hokimi, 2001–2003-yillarda Samarqand viloyati hokimi lavozimlarida ishlagan, ushbu hududlarning ijtimoiy-iqtisodiy rivojlanishiga katta hissa qo‘shgan.
  Ijro etuvchi hokimiyat organlarida ishlash bilan birga, 1995–2003-yillarda O‘zbekiston Respublikasi Oliy Majlisi deputati sifatida mamlakatning siyosiy va ijtimoiy-iqtisodiy rivojlanishi, demokratik islohotlarning amalga oshirilishiga qaratilgan muhim qonunchilik hujjatlarini ishlab chiqish va qabul qilishda faol ishtirok etgan.
  2003-yilda Sh.M. Mirziyoyev O‘zbekiston Respublikasi Bosh vaziri lavozimiga tasdiqlandi va ushbu lavozimga 2005, 2010, 2015-yillarda yana uch marta Oliy Majlis palatalari tomonidan tasdiqlandi.
  Vatanimiz mustaqilligining dastlabki yillaridan boshlab, Sh.M. Mirziyoyev O‘zbekiston Respublikasining Birinchi Prezidenti Islom Karimovning yuksak ishonchini qozongan holda, uning safdoshi va hamfikri sifatida fidokorona mehnat qilgan.
  Hukumat rahbari sifatida Sh.M. Mirziyoyev yirik ijtimoiy-iqtisodiy islohotlarni amalga oshirish, mamlakatni modernizatsiya qilish va yangilash, yirik va noyob loyihalarni amalga oshirish, xususiy mulkning ustuvorligini ta’minlash, kichik biznes va xususiy tadbirkorlikning iqtisodiyotdagi ulushini keskin oshirish hamda ularning huquqiy himoyasini yanada mustahkamlash borasida o‘zining yuqori salohiyati va buyuk tashkiliy qobiliyatini namoyon etdi.
    `,
    en: `
  Shavkat Miromonovich Mirziyoyev was born on July 24, 1957, in the Zomin district of the Jizzakh region in a family of a doctor. He is Uzbek by nationality. He received higher education and graduated in 1981 from the Tashkent Institute of Irrigation and Agricultural Mechanization Engineers with a degree in mechanical engineering. He holds a PhD in Technical Sciences and the academic title of Associate Professor.
  He began his career in 1981 at the same institute, working as a junior researcher, senior lecturer, associate professor, and vice-rector for academic affairs.
  In 1990, he was elected deputy of the Supreme Council of the Republic and served as Chairman of the Mandate Commission.
  In 1992, he was appointed as the hokim (governor) of the Mirzo-Ulugbek district of Tashkent city. From 1996 to 2001, he served as the hokim of the Jizzakh region, and from 2001 to 2003, as the hokim of the Samarkand region, making a significant contribution to the socio-economic development of these areas.
  While working in executive government bodies, he also served from 1995 to 2003 as a deputy of the Oliy Majlis (Parliament) of the Republic of Uzbekistan, actively participating in the development and adoption of important legislative acts aimed at the political and socio-economic development of the country and the implementation of democratic reforms.
  In 2003, Sh.M. Mirziyoyev was approved as Prime Minister of the Republic of Uzbekistan, and was reapproved for this post by the chambers of the Oliy Majlis in 2005, 2010, and 2015.
  From the early years of our country’s independence, Sh.M. Mirziyoyev earned the high trust of the First President of the Republic of Uzbekistan, Islam Karimov, and worked devotedly as his associate and like-minded colleague.
  As head of government, Sh.M. Mirziyoyev demonstrated his high potential and outstanding organizational skills in carrying out large-scale socio-economic reforms, modernization and renewal of the country, implementation of major and unique projects, development and prioritization of private property, substantial increase in the share of small business and private entrepreneurship in the economy, and further strengthening of their legal protection.
    `
  };
  