export const HISTORY_MISSION = {
    title: {
      ru: "Хронология развития посольства",
      uz: "Elchixonaning rivojlanish xronologiyasi",
      en: "Chronology of the Embassy's Development"
    },
    description: {
      ru: `Дипломатические отношения между Украиной и Республикой Узбекистан установлены 25 августа 1992 года. 28 октября 1991 года был подписан Договор об основах межгосударственных отношений, дружбе и сотрудничестве и Протокол о консультациях между министерствами иностранных дел двух стран.Дипломатическое представительство Украины в Республике Узбекистан было открыто в 1993г. Посольство Республики Узбекистан в Украине действует с 1995г.
  Здание по адресу Владимирская 16 было сооружено в 1879-1881 годах в стиле эклектика по проекту архитектора В.Н.Николаева для чиновника Ф.М.Чарнецкого. Земельный участок площадью 1789 м2, на котором расположен объект, находится в Шевченковском районе горда Киев, с восточной стороны ограничен тротуаром на ул. Владимирской, с северной и западной - территорией НИПИ Градостроительства и детского учреждения, с южной стороны-с участком граничит прилегающая территория 5-ти этажного жилого дома.
  Г-образное 4-х этажное здание с подвалом площадью 2885,8м2 стоит на фундаменте из набивных железобетонных свай, установленных по безударной технологии. В кирпичных стенах на уровне железобетонных междуэтажных перекрытий устроены замкнутые монолитные железобетонные пояса, стены частично усилены железобетонными колоннами, внешние стены утеплены минераловатными плитами толщиной 75 мм.
  Ф.М.Чарнецкий сдавал дом в аренду, меблированные комнаты на 10 номеров, где жили горожане среднего достатка и останавливались приезжие. Среди них - русские художники М.А.Врубель (1888) и М.В.Нестеров (1890).
  В 1982 году Старокиевская пожарная команда успешно испытала на этом здании новую машину для спасения больных и детей.
  В конце XIX века у дома появляется новый владелец, который превращает меблированные комнаты на отель «Liondor». Отель существовал до начала прошлого века, когда его помещение приспособили под учебное заведение. Сменяя друг друга, в здании содержались мужская гимназия В.И.Петра, Первая гимназия Совета родителей и, наконец, гимназия В.А.Жеребцовой. Это учебное заведение считалось одним из лучших в Киеве и с 1 августа 1911 года находилось в этом доме. При советской власти в доме работал Кооперативный музей «Днипроспилки», которым 1920 г. руководил П.Г.Тычина.
  С 2003 года в здании размещено Посольство Республики Узбекистан в Украине.
  В 2013-2015 годах в здании узбекскими мастерами проведены ремонтно-восстановительные работы. Народными мастерами Узбекистана Махаматали Юнусовым и Мансуржон Муродовым, а также мастером из Хивинского района Хорезмской области Курбанбай Исмаиловым совместно с учениками в национальном стиле возведены во дворе и внутри здания деревянные резные беседки, колонны, резьбы по ганчу на стенах, карнизы, арки и двери. Заменены входные двери на резные двери со стороны улицы Владимирской. Для работы узбекские мастера использовали украинскую древесину - сосну и дуб.
  Также в 2013 году рядом со зданием Посольства был установлен телеэкран, на котором круглые сутки осуществляется показ видеороликов о туристическом потенциале Узбекистана.`,
      
      uz: `Ukraina va O‘zbekiston Respublikasi o‘rtasida diplomatik munosabatlar 1992-yil 25-avgustda o‘rnatilgan. 1991-yil 28-oktabrda ikki davlat Tashqi ishlar vazirliklari o‘rtasida maslahatlashuvlar protokoli va davlatlararo munosabatlar, do‘stlik va hamkorlik asoslari to‘g‘risidagi Shartnoma imzolangan. Ukrainada O‘zbekiston elchixonasi 1995-yildan buyon faoliyat yuritadi, Ukraina vakolatxonasi esa O‘zbekistonda 1993-yilda ochilgan.
  Vladimirskaya ko‘chasi 16-uydagi bino 1879–1881 yillarda arxitektor V.N.Nikolaev loyihasi asosida eklektika uslubida F.M.Charnetskiy uchun qurilgan. Maydoni 1789 m² bo‘lgan uchastka Kiyevning Shevchenko tumanida joylashgan. Sharqdan — Vladimirskaya ko‘chasi, shimol va g‘arbdan — shaharsozlik instituti va bolalar muassasasi, janubdan esa besh qavatli uy hovlisi bilan chegaradosh.
  To‘rt qavatli, G-shaklidagi binoning maydoni 2885,8 m² bo‘lib, zarbasiz texnologiya asosida beton ustunlarga o‘rnatilgan. Devorlari mustahkamlangan, tashqi devorlar 75 mm qalinlikdagi mineral paxta plitalari bilan issiqlik izolyatsiyalangan.
  F.M.Charnetskiy ushbu binoni ijaraga bergan — o‘rta daromadli shaharliklar va sayohatchilar uchun 10 ta mebellangan xona mavjud bo‘lgan. Bu yerda mashhur rus rassomlari M.A.Vrubel (1888) va M.V.Nesterov (1890) ham yashagan.
  1982-yilda Starokiev yong‘in xizmati ushbu binoda yangi qutqaruv texnikasini sinovdan o‘tkazgan.
  XIX asr oxirida bino yangi egasiga o‘tib, u “Liondor” mehmonxonasiga aylantirilgan. Keyinchalik, bu bino bir nechta o‘quv dargohlariga aylantirildi: V.I.Petra erkaklar gimnaziyasi, Ota-onalar kengashi birinchi gimnaziyasi, nihoyat V.A.Jerebtsova gimnaziyasi. 1911-yil 1-avgustdan bu yerda faoliyat yuritgan.
  Sovet davrida bu yerda “Dniprosilkalar” kooperativ muzeyi joylashgan, 1920-yilda unga P.G.Tychina rahbarlik qilgan.
  2003-yildan buyon bu binoda O‘zbekiston Respublikasining Ukrainadagi elchixonasi joylashgan.
  2013–2015-yillarda binoda o‘zbek ustalari tomonidan ta’mirlash va restavratsiya ishlari olib borilgan. Xorazm viloyati, Xiva tumanidan bo‘lgan usta Qurbonboy Ismoilov, xalq ustalari Mahamatali Yunusov va Mansurjon Murodov hamda ularning shogirdlari tomonidan milliy uslubda yog‘ochdan o‘yma ayvonlar, ustunlar, ganch o‘ymakorligi, karnizlar, arkalar va eshiklar tayyorlangan. Kirish eshiklari Vladimirskaya ko‘chasi tomonidan o‘yilgan eshiklar bilan almashtirilgan. Ustalar ukrain yog‘ochi — qarag‘ay va eman — dan foydalangan.
  Shuningdek, 2013-yilda elchixona binosi yaqinida O‘zbekistonning turistik salohiyati haqida videoroliklar namoyishi uchun doimiy ishlovchi monitor o‘rnatilgan.`,
      
      en: `Diplomatic relations between Ukraine and the Republic of Uzbekistan were established on August 25, 1992. On October 28, 1991, the Treaty on the Fundamentals of Interstate Relations, Friendship, and Cooperation, along with the Protocol on Consultations between the Ministries of Foreign Affairs of both countries, was signed. Ukraine’s diplomatic mission in Uzbekistan opened in 1993, and the Embassy of the Republic of Uzbekistan in Ukraine has been operating since 1995.
  The building at 16 Volodymyrska Street was constructed between 1879–1881 in eclectic style by architect V.N. Nikolaev for civil servant F.M. Charnetsky. The land plot (1789 m²) is located in the Shevchenkivskyi district of Kyiv. It is bordered by Volodymyrska Street to the east, an urban planning institute and a childcare institution to the north and west, and a five-story residential building’s courtyard to the south.
  The L-shaped, four-story building with a basement has an area of 2885.8 m² and stands on reinforced concrete piles installed using a non-impact technology. The brick walls are reinforced with concrete belts at the slab levels, partially supported by columns, and externally insulated with 75 mm mineral wool panels.
  F.M. Charnetsky rented the house out as furnished rooms (10 units), used by middle-class residents and travelers. Among them were Russian artists M.A. Vrubel (1888) and M.V. Nesterov (1890).
  In 1982, Kyiv’s old fire brigade tested a new rescue vehicle for patients and children on this site.
  At the end of the 19th century, a new owner converted the rooms into the “Liondor” hotel. The hotel operated until the early 20th century, after which the building became an educational institution: the V.I. Petra boys’ gymnasium, the First Parent Council Gymnasium, and finally the V.A. Zherebtsova Gymnasium, considered one of Kyiv’s best since August 1, 1911.
  During the Soviet period, the “Dniprospilka” Cooperative Museum operated here under the leadership of P.G. Tychyna in 1920.
  Since 2003, the building has housed the Embassy of the Republic of Uzbekistan in Ukraine.
  Between 2013 and 2015, Uzbek artisans carried out restoration work. Master craftsmen Mahamatali Yunusov and Mansurjon Murodov, along with Kurbanbay Ismailov from Khiva district (Khorezm region), and their students, created wooden carved gazebos, columns, ganch decorations, cornices, arches, and doors in the national style. The entrance doors facing Volodymyrska Street were replaced with carved wooden ones. Uzbek artisans used Ukrainian wood — pine and oak.
  Also in 2013, a digital screen was installed near the Embassy building to display video content on Uzbekistan’s tourism potential 24/7.`
    }
  };
  