export const PREZIDENT_INFO = {
    ru: `
      Шавкат Миромонович Мирзиёев родился 24 июля 1957 года в Зааминском районе Джизакской области в семье врача. По национальности – узбек. Образование – высшее, в 1981 году окончил Ташкентский институт инженеров ирригации и механизации сельского хозяйства, получив специальность инженера-механика. Кандидат технических наук, доцент.
      Начал трудовую деятельность в 1981 году в Ташкентском институте инженеров ирригации и механизации сельского хозяйства, работал младшим научным сотрудником, старшим преподавателем, доцентом, проректором по учебной работе.
      В 1990 году избран депутатом Верховного Совета республики, был председателем Мандатной комиссии.
      В 1992 году был назначен хокимом Мирзо-Улугбекского района города Ташкента. В 1996–2001 годах работал в должности хокима Джизакской области, в 2001–2003 годах – хокимом Самаркандской области, внес большой вклад в социально-экономическое развитие вышеназванных районов и областей.
      Работая в органах исполнительной власти, одновременно в 1995–2003 годах в качестве депутата Олий Мажлиса Республики Узбекистан активно и плодотворно участвовал в разработке и принятии важных законодательных документов, направленных на политическое и социально-экономическое развитие страны и реализацию демократических реформ.
      Ш.М. Мирзиёев в 2003 году был утвержден Премьер-министром Республики Узбекистан и ещё три раза – в 2005, 2010, 2015 годах – утверждался на этот пост палатами Олий Мажлиса.
      С первых лет независимости нашей Родины Ш.М. Мирзиёев, заслужив высокий доверие Первого Президента Республики Узбекистан Ислама Каримова, самоотверженно работает как его соратник и единомышленник.
      На посту главы правительства он проявил высокий потенциал и выдающиеся организаторские способности в реализации широкомасштабных социально-экономических реформ, модернизации и обновлении страны, осуществлении крупных и уникальных проектов, развитии и обеспечении приоритета частной собственности, кардинальном повышении доли малого бизнеса и частного предпринимательства в экономике и дальнейшем укреплении их правовой защиты.
      Особое внимание в своей работе он уделял развитию экономики на индустриальной основе, повышению экспортного потенциала страны, коренному реформированию аграрной сферы, в первую очередь широкому развитию фермерского движения, глубокой переработке сельскохозяйственной продукции, обеспечению продовольственной безопасности республики и гарантированному обеспечению населения потребительскими товарами по доступным ценам.
      В целях кардинального улучшения условий жизни и труда населения Ш.М. Мирзиёевом были приняты эффективные меры по масштабному строительству и благоустройству во всех регионах страны, повышению качества коммунальных услуг, комплексному развитию городов и районов республики, особенно отдаленных сельских районов.
      В деятельности Ш.М. Мирзиёева наряду с социально-экономическим направлением важное место занимали вопросы развития сфер образования, науки и здравоохранения, создания условий для формирования здорового и гармонично развитого молодого поколения, усиления охраны материнства и детства.
      Большое внимание уделялось дальнейшему повышению авторитета уникального института самоуправления – махалли, а также сохранению и приумножению национальных духовных ценностей.
      Одновременно с выполнением экономических и социальных задач, он непосредственно руководил укреплением всестороннего взаимовыгодного сотрудничества с зарубежными странами, международными структурами, финансовыми институтами и заключением важных соглашений, отвечающих национальным интересам и способствующих экономическому развитию страны.
      8 сентября 2016 года, на основании совместного постановления Законодательной палаты и Сената Олий Мажлиса Республики Узбекистан, на Ш.М. Мирзиёева было временно возложено исполнение обязанностей и полномочий Президента Республики Узбекистан.
      VIII съезд Движения предпринимателей и деловых людей — Либерально-демократической партии Узбекистана (УзЛиДеП), состоявшийся в Ташкенте 19 октября, принял решение о выдвижении члена политического совета партии Шавката Миромоновича Мирзиёева кандидатом в Президенты. По итогам президентских выборов 4 декабря 2016 года, он был избран Президентом Республики Узбекистан, набрав 88,61% голосов избирателей. Официально вступил в должность 14 декабря 2016 года.
      24 октября 2021 года Президент Шавкат Мирзиёев был переизбран на второй пятилетний срок, набрав 80,1% голосов избирателей.
      Ш.М. Мирзиёев женат, имеет двух дочерей, одного сына и пять внуков. Супруга З.М. Мирзиёева – по образованию инженер-экономист, в настоящее время – домохозяйка.
      За многолетний плодотворный труд в органах государственной власти и управления, огромный вклад в развитие страны и повышение благосостояния народа, Ш.М. Мирзиёев награждён орденами «Мехнат шухрати» и «Фидокорона хизматлари учун».
    `,
    uz: `
      Shavkat Miromonovich Mirziyoyev 1957-yil 24-iyulda Jizzax viloyatining Zaamin tumanida, shifokor oilasida tug‘ilgan. Millati – o‘zbek. Ta'limi – oliy, 1981-yilda Toshkent Irrigatsiya injenerlari va qishloq xo‘jaligi mexanizatsiyasi institutini tamomlagan, mexanik muhandis ixtisosligini olgan. Texnika fanlari nomzodi, dotsent.
      1981-yilda Toshkent Irrigatsiya injenerlari va qishloq xo‘jaligi mexanizatsiyasi institutida ish faoliyatini boshlagan: avval ilmiy xodim, keyin katta o‘qituvchi, dotsent va ta’lim ishlaridan mas’ul prorektor sifatida xizmat qilgan.
      1990-yilda Respublikamiz Oliy Kengashining deputati sifatida saylangan, Mandat komissiyasi raisi bo‘lgan.
      1992-yilda Toshkent shahridagi Mirzo Ulug‘bek tumani hokimi lavozimiga tayinlangan. 1996–2001 yillarda Jizzax viloyati hokimi, 2001–2003 yillarda esa Samarqand viloyati hokimi bo‘lib, yuqorida tilga olingan hududlarning ijtimoiy-iqtisodiy rivojlanishiga katta hissa qo‘shgan.
      Ijro etuvchi organlarda faoliyat yuritgan davrida, 1995–2003 yillarda Respublika Oliy Majlisi deputati sifatida mamlakatning siyosiy va ijtimoiy-iqtisodiy rivojlanishi, shuningdek, demokratik islohotlarni amalga oshirishga qaratilgan muhim qonunchilik hujjatlarini ishlab chiqish va qabul qilishda faol ishtirok etgan.
      2003-yilda Sh.M. Mirziyoyevni O‘zbekiston Prezidenti o‘rniga vaqtincha Prezident vazifasini bajarishga tayinlagan va 2005, 2010, 2015-yillarda Oliy Majlis palatalari tomonidan ushbu lavozimga qayta tasdiqlagan.
      Mustaqillikning dastlabki yillaridan boshlab, O‘zbekistonning birinchi Prezidenti Islom Karimovning katta ishonchini qozongan Sh.M. Mirziyoyev, o‘zining fidoyi mehnati bilan uning yaqin hamkori va fikrdo‘sti sifatida faol ishlaydi.
      Hukumat rahbari sifatida u keng ko‘lamli ijtimoiy-iqtisodiy islohotlarni amalga oshirish, mamlakatni modernizatsiya va yangilash, yirik va noyob loyihalarni hayotga tadbiq etish, xususiy mulkka ustuvorlik berish, kichik biznes va xususiy tadbirkorlik ulushini keskin oshirish hamda ularning huquqiy himoyasini mustahkamlash borasida o‘zining yuqori salohiyatini va ajoyib tashkiliy qobiliyatlarini namoyish etdi.
      U o‘z faoliyatida sanoat asosidagi iqtisodiyotni rivojlantirish, mamlakatning eksport salohiyatini oshirish, qishloq xo‘jaligi sohasida tub islohotlar o‘tkazish, ayniqsa fermerlar harakatining keng rivojlanishi, qishloq xo‘jalik mahsulotlarini chuqur qayta ishlash, respublika oziq-ovqat xavfsizligini ta’minlash va aholiga arzon narxlarda iste’mol tovarlarini yetkazib berishga katta e’tibor qaratdi.
      Aholi yashash va mehnat sharoitlarini tubdan yaxshilash maqsadida, Sh.M. Mirziyoyev tomonidan mamlakatning barcha hududlarida keng ko‘lamli qurilish va muhitni yaxshilash, kommunal xizmatlar sifatini oshirish, shahar va tumanlarning kompleks rivojlanishi, xususan qishloqning chekka hududlarini rivojlantirish bo‘yicha samarali choralar ko‘rildi.
      Sh.M. Mirziyoyev faoliyatida ijtimoiy-iqtisodiy soha bilan bir qatorda, ta’lim, fan va sog‘liqni saqlash sohalarini rivojlantirish, sog‘lom va uyg‘un rivojlangan avlodni shakllantirish uchun zarur sharoitlarni yaratish, ona va bola salomatligini mustahkamlash kabi masalalarga ham katta e’tibor qaratildi.
      Shuningdek, u mahalla va boshqa jamoat tashkilotlari kabi o‘ziga xos o‘zini boshqarish institutining obro‘sini oshirish, keng jamoatchilikni demokratik islohot jarayonlariga jalb etish va milliy ruhiy qadriyatlarni asrash va rivojlantirishga doir masalalarni puxta amalga oshirdi.
      Shu bilan birga, iqtisodiy va ijtimoiy vazifalarni bajarish jarayonida xorijiy davlatlar, xalqaro tuzilmalar, moliyaviy institutlar bilan o‘zaro foydali hamkorlikni mustahkamlash va mamlakat manfaatlariga mos keluvchi muhim kelishuvlar imzolash ishlarini ham bevosita boshqardi.
      8-sentabr 2016-yilda O‘zbekiston Respublikasi Oliy Majlisining Qonunchilik palatasi va Senati qo‘shma qarori asosida, Sh.M. Mirziyoyevga Prezident vazifalari va vakolatlarini vaqtincha yuklash qarori qabul qilindi.
      Toshkentda 19-oktabr kuni o‘tkazilgan O‘zbekiston Liberal-demokratik partiyasi (UzLiDeP) Tadbirkorlar va Biznesmenlar harakati VIII kongressi partiya siyosiy kengashining a’zosi Shavkat Miromonovich Mirziyoyevni Prezident nomzodi sifatida taklif qildi. 4-dekabr 2016-yilda o‘tkazilgan Prezident saylovlari natijasida, u 88,61% ovoz bilan O‘zbekiston Respublikasi Prezidenti etib saylandi va 14-dekabr 2016-yilda rasmiy ravishda ishga kirishdi.
      24-oktabr 2021-yilda Prezident Shavkat Mirziyoyev ikkinchi besh yillik muddatga qayta saylandi, 80,1% ovoz to‘pladi.
      Sh.M. Mirziyoyev turmushga chiqqan, ikki qizi, bir o‘g‘li va beshta nevaraga ega. Uning rafiqasi Z.M. Mirziyoyeva – ta’limi bo‘yicha injener-iqtisodist, hozirda uy bekasi.
      Davlat boshqaruvi va idoralarida uzoq yillik samarali faoliyati, mamlakat rivojlanishi va xalq farovonligini oshirishga qo‘shgan ulkan hissasi evaziga, Sh.M. Mirziyoyev «Mehnat shon-shuhrati» va «Fidokorona xizmatlari uchun» ordenlari bilan taqdirlangan.
    `,
    en: `
      Shavkat Miromonovich Mirziyoyev was born on July 24, 1957, in the Zaamin district of the Jizzakh region into a family of a doctor. He is of Uzbek nationality. He received a higher education and graduated in 1981 from the Tashkent Institute of Irrigation Engineers and Mechanization of Agriculture, obtaining the qualification of a mechanical engineer. He is a Candidate of Technical Sciences and an Associate Professor.
      He began his professional career in 1981 at the Tashkent Institute of Irrigation Engineers and Mechanization of Agriculture, working as a junior researcher, then as a senior lecturer, associate professor, and eventually as the Vice-Rector for Academic Affairs.
      In 1990, he was elected as a deputy to the Supreme Council of the Republic and served as the chairman of the Mandate Commission.
      In 1992, he was appointed as the Hokim (governor) of the Mirzo Ulugbek district of Tashkent. From 1996 to 2001 he served as the Hokim of the Jizzakh region, and from 2001 to 2003 as the Hokim of the Samarkand region, making significant contributions to the socio-economic development of the respective districts and regions.
      While working in the executive branch, he also actively participated as a deputy of the Oliy Majlis (Parliament) of the Republic of Uzbekistan from 1995 to 2003, contributing to the drafting and adoption of important legislative documents aimed at the political and socio-economic development of the country and the implementation of democratic reforms.
      In 2003, Mirziyoyev was confirmed as Prime Minister of the Republic of Uzbekistan, and he was reconfirmed in this position by the chambers of the Oliy Majlis in 2005, 2010, and 2015.
      From the early years of the country’s independence, Sh.M. Mirziyoyev, having earned the high trust of the First President of Uzbekistan, Islam Karimov, has been working selflessly as his close associate and like-minded partner.
      As the head of government, he demonstrated his high potential and outstanding organizational skills in implementing large-scale socio-economic reforms, modernizing and renewing the country, carrying out major and unique projects, promoting the priority of private ownership, significantly increasing the share of small businesses and private entrepreneurship in the economy, and further strengthening their legal protection.
      He paid special attention to developing an industrial-based economy, increasing the country’s export potential, and undertaking comprehensive reforms in the agricultural sector—especially through the expansion of the farming movement, deep processing of agricultural products, ensuring the republic’s food security, and guaranteeing the provision of consumer goods to the population at affordable prices.
      In order to radically improve living and working conditions, effective measures were taken under his leadership for large-scale construction and beautification in all regions of the country, enhancement of the quality of communal services, and comprehensive development of cities and districts, particularly remote rural areas.
      Alongside socio-economic development, significant efforts were also made to advance the fields of education, science, and healthcare, create favorable conditions for raising a healthy and well-balanced new generation, and strengthen the protection of motherhood and childhood.
      Moreover, he focused on further enhancing the prestige of the unique self-government institution – the mahalla – and other public organizations, ensuring their growing influence in society through broad public involvement in the process of democratic reforms, as well as preserving and enhancing national spiritual values.
      At the same time, while carrying out economic and social tasks, he directly led efforts to strengthen mutually beneficial cooperation with foreign countries, international organizations, and financial institutions, and to conclude important agreements that serve the national interests and contribute to the economic development of the country.
      On September 8, 2016, by a joint resolution of the Legislative Chamber and the Senate of the Oliy Majlis of the Republic of Uzbekistan, Mirziyoyev was temporarily entrusted with the duties and powers of the President of the Republic of Uzbekistan.
      At the VIII Congress of the Movement of Entrepreneurs and Businesspeople – the Liberal Democratic Party of Uzbekistan (UzLiDeP), held in Tashkent on October 19, the party’s Political Council member Shavkat Miromonovich Mirziyoyev was nominated as the presidential candidate. In the presidential elections held on December 4, 2016, he was elected as the President of the Republic of Uzbekistan with 88.61% of the vote, and he officially assumed office on December 14, 2016.
      On October 24, 2021, President Shavkat Mirziyoyev was re-elected for a second five-year term, receiving 80.1% of the vote.
      Sh.M. Mirziyoyev is married, has two daughters, one son, and five grandchildren. His wife, Z.M. Mirziyoyeva, is a trained engineer-economist and currently a homemaker.
      In recognition of his many years of productive work in state governance and administration, as well as his tremendous contribution to the development of the country and the improvement of the people's welfare, Sh.M. Mirziyoyev has been awarded the orders "Mehnat shon-shuhrati" and "Fidokorona xizmatlari uchun."
    `,
  };
  